### ISSUE TITLE
Summersloops and Spehres are not marked as collected, when uploading a 1.0 save

### ISSUE THREAD

**Issue by Sonic4080** [AnthorNet/SC-InteractiveMap#333] opened 2024-09-17 22:32 UTC
# Issue
Summersloops and Mercer Spheres are not marked as collected, when a 1.0 savefile is uploaded. (Harddrives still work, idk why)

## Replication
Upload a savefile from the 1.0 Version of the game, in wich some sloops/spehres have been collected. Then highlight the sloops/spehres in the artifacts menu.

### Actual Result
All sloops/spheres are fully visible.

### Expected Result
Only the still available sloops/spheres are fully visible, the allready collected ones should be partially transparent.

Here is a screenshot. Simmilar to the Harddrives, the close by Spheres and Sloops have been collected.
![saty_calc_issue](https://github.com/user-attachments/assets/1ab53fcb-0242-406e-9190-624129ca396f)

**Comment by AnthorNet** [comment] 2024-09-18 07:25
Please send your save, I wasn't able to reproduce!
![image](https://github.com/user-attachments/assets/e55d080f-8fff-45a4-b2f8-dbf222c46abd)

**Comment by Sonic4080** [comment] 2024-09-18 19:39
[1oo_08.zip](https://github.com/user-attachments/files/17049399/1oo_08.zip)
Here is the file. I tried it with Firefox, Chrome and Edge, all three browsers have the problem.

**Comment by AnthorNet** [comment] 2024-09-19 08:02
![image](https://github.com/user-attachments/assets/3a891352-101e-4dd8-90fb-69190bcf1188)

There is nothing in the save saying they were collected, so could be an in-game bug.
Checked in-game if they haven't respawn?

If nothing is in the save, I'll close the issue as it's not related to SCIM it seems.

**Comment by AnthorNet** [comment] 2024-09-23 07:40
Checking that again :)

**Comment by AnthorNet** [comment] 2024-09-23 07:56
Something I see on your screenshot is that you're missing the collected and the rest I've checked in game seems to be coherent?
Are you sure you have this option enabled? (Show collected on map?)

![image](https://github.com/user-attachments/assets/ca683f7a-083f-4021-9ea5-98cec83bbe8d)

**Comment by AnthorNet** [comment] 2024-09-23 10:04
Fixed (Need a couple more testing)

**Closed as completed by AnthorNet** 2024-09-23 10:04 UTC
Labels: bug

**Comment by Sonic4080** [comment] 2024-09-23 17:11
> Something I see on your screenshot is that you're missing the collected and the rest I've checked in game seems to be coherent? Are you sure you have this option enabled? (Show collected on map?)
> 

yes that option was activated



> Fixed (Need a couple more testing)


can confirm, it works now.
Thanks for the quick fix!
