### ISSUE TITLE
No Cables in pasted factories in game

### ISSUE THREAD

**Issue by GiBDargeth** [AnthorNet/SC-InteractiveMap#211] opened 2022-05-01 20:08 UTC
Hi, having an issue when pasting factories, I've tried countless of times it copies over everything but the cables, in the calc it is fine but not in game, examples in the pictures, thanks

![image](https://user-images.githubusercontent.com/54288200/166162668-608f9142-ba14-4f3e-bb8a-11b265ae8b2f.png)
![image](https://user-images.githubusercontent.com/54288200/166162691-28f0bf20-052f-4d13-a7df-90d7d14cedd2.png)

**Comment by AnthorNet** [comment] 2022-05-02 06:50
Still need the files in order to inspect them after my holidays ;)

**Comment by GiBDargeth** [comment] 2022-05-02 10:42
Sent you the files via email, btw while experimenting with single player cables do show up but then on my Dedicated server it seems that the cables don't show up but they are there, on my Dedicated server I've also noticed that copied and pasted Oil and Water Extractors keep on working regardless if they are not on a node. I suppose it is a Dedicated Server issue rather than a calc issue

**Comment by AnthorNet** [comment] 2022-05-02 13:59
Haven't received by email? Where did you send the files?

**Comment by GiBDargeth** [comment] 2022-05-02 17:35
I replied to the email containing this convo as I cannot paste the .sav files here it says it is not supported :/

**Comment by GiBDargeth** [comment] 2022-05-02 17:45
Here is the saves and the blueprint
https://www.dropbox.com/sh/w0ld98e5x3ox4ui/AAA7k8nij4PV9fq1gdQalyKka?dl=0

**Comment by AnthorNet** [comment] 2022-05-06 08:19
I still have no clue about this issue :)

**Comment by GiBDargeth** [comment] 2022-05-06 09:19
Hi, basically whatever factory I copy paste in my save and when opend in my dedicated server the cables are invisible but everything works

**Comment by AnthorNet** [comment] 2022-05-06 09:21
Is the dedicated server throwing anything in the logs?

**Comment by GiBDargeth** [comment] 2022-05-06 09:21
No everything is fine

**Comment by AnthorNet** [comment] 2022-05-06 09:23
What if you load/save in solo before trying it in server?

**Comment by AnthorNet** [comment] 2022-05-06 09:25
Thanks, trying to find where the issue could be :)

**Comment by AnthorNet** [comment] 2022-05-06 14:11
I had no luck reproducing the issue on my test save

**Comment by GiBDargeth** [comment] 2022-05-06 21:28
Ok, so it worked I opened the save in single player, saved the session, copied it over to the server, run the server and presto it worked, phew what a process lol, thank you for your help AnthorNet ;)

**Comment by AnthorNet** [comment] 2022-05-07 05:24
Cool, glad it worked for you. I'll close it for now as I couldn't reproduce it myself.

**Closed by AnthorNet** 2022-05-07 05:24 UTC

**Comment by GiBDargeth** [comment] 2022-05-07 18:44
Hey, it worked because I imported a blueprint from the website but if I copy paste with lasso tool then save the blueprint on my desktop, import the blueprint, paste it, save the file, open it in single player ( which is fine) when I import it to my dedicated server the cables are not visible, weird huh!!
