### ISSUE TITLE
[Feature Request] map image export

### ISSUE THREAD

**Issue by wtodom** [AnthorNet/SC-InteractiveMap#402] opened 2024-12-01 22:07 UTC
I personally love seeing images of people's saves from the Interactive Map, and I also love looking over mine and sharing it with friends too. However, right now it seems like there are two options for doing so, and both are a bit...unsatisfactory. One is taking a screenshot of the full map on the site, but that has the downside that it's relatively small if you want the full world on it. The other option is to zoom in close enough that you can see enough detail and take multiple screenshots, but then you have to take time afterwards to stitch together all those images which can be tedious and error-prone. I'd love it if there was a way to export an image of your save's loaded map, complete with whatever layers and such are currently active, at a reasonable zoom level (perhaps just whatever the current zoom was, applied to the whole image).

I haven't personally worked on this exact kind of project before and realistically I'm more experience on the backend side that with highly interactive frontend features, but I'd be happy to at least try getting familiar with the codebase and working on a prototype if this sort of feature if something you'd be interested adding to the site. I look forward to hearing your responese; thanks for reading!

**Comment by AnthorNet** [comment] 2024-12-02 08:32
Duplicate of #392

**Closed as completed by AnthorNet** 2024-12-02 08:32 UTC
Labels: enhancement
