### ISSUE TITLE
Map Colour Settings export/import

### ISSUE THREAD

**Issue by meza** [AnthorNet/SC-InteractiveMap#47] opened 2021-03-18 16:34 UTC
It would be nice to be able to export and import colour themes for the colour slots in both the gun and the lights so that reusing the same settings in multiple save files would become simpler.

I'd love to be able to set it up once, save it and then re-use my personal theme.

**Comment by AnthorNet** [comment] 2021-03-18 16:57
Duplicate of #19

**Closed by AnthorNet** 2021-03-18 16:57 UTC
